"""add_sort_order_to_task_lists_and_app_settings

Revision ID: 52a321b44f51
Revises: 873480fc4e0c
Create Date: 2026-03-05 07:48:34.031867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a321b44f51'
down_revision: Union[str, Sequence[str], None] = '873480fc4e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('task_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # Assign sequential sort_order to existing task lists ordered by id
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM task_lists ORDER BY id")).fetchall()
    for i, row in enumerate(rows):
        conn.execute(
            sa.text("UPDATE task_lists SET sort_order = :order WHERE id = :id"),
            {"order": (i + 1) * 10, "id": row[0]},
        )

    # Default overdue position: after all regular lists (9999)
    conn.execute(
        sa.text("INSERT INTO app_settings (key, value) VALUES ('overdue_sort_order', '9999')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_lists', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
