"""add indexes on FK and query columns

Revision ID: 6c2a0b806044
Revises: a8b46995a372
Create Date: 2026-03-04 22:10:43.874493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2a0b806044'
down_revision: Union[str, Sequence[str], None] = 'a8b46995a372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_events_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_events_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_events_start_time'), ['start_time'], unique=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_cook_member_id'), ['cook_member_id'], unique=False)

    with op.batch_alter_table('recurrence_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrence_series_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('task_recurrence_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_recurrence_series_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_recurrence_series_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_series_id'), ['series_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_series_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_member_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_list_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_done'))

    with op.batch_alter_table('task_recurrence_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_recurrence_series_member_id'))
        batch_op.drop_index(batch_op.f('ix_task_recurrence_series_list_id'))

    with op.batch_alter_table('recurrence_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrence_series_member_id'))

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_cook_member_id'))

    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_agenda_events_series_id'))
        batch_op.drop_index(batch_op.f('ix_agenda_events_member_id'))

    # ### end Alembic commands ###
