"""multi_member_m2m

Revision ID: 873480fc4e0c
Revises: 6c2a0b806044
Create Date: 2026-03-04 22:24:54.835816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873480fc4e0c'
down_revision: Union[str, Sequence[str], None] = '6c2a0b806044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing = inspector.get_table_names()

    if 'recurrence_series_members' not in existing:
        op.create_table('recurrence_series_members',
        sa.Column('series_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['series_id'], ['recurrence_series.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('series_id', 'member_id')
        )
    if 'agenda_event_members' not in existing:
        op.create_table('agenda_event_members',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['agenda_events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('event_id', 'member_id')
        )
    if 'task_recurrence_series_members' not in existing:
        op.create_table('task_recurrence_series_members',
        sa.Column('series_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['series_id'], ['task_recurrence_series.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('series_id', 'member_id')
        )
    if 'task_members' not in existing:
        op.create_table('task_members',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', 'member_id')
        )

    # Drop member_id columns if they still exist
    agenda_cols = [c['name'] for c in inspector.get_columns('agenda_events')]
    if 'member_id' in agenda_cols:
        with op.batch_alter_table('agenda_events', schema=None) as batch_op:
            try:
                batch_op.drop_index(batch_op.f('ix_agenda_events_member_id'))
            except Exception:
                pass
            batch_op.drop_column('member_id')

    series_cols = [c['name'] for c in inspector.get_columns('recurrence_series')]
    if 'member_id' in series_cols:
        with op.batch_alter_table('recurrence_series', schema=None) as batch_op:
            try:
                batch_op.drop_index(batch_op.f('ix_recurrence_series_member_id'))
            except Exception:
                pass
            batch_op.drop_column('member_id')

    tr_cols = [c['name'] for c in inspector.get_columns('task_recurrence_series')]
    if 'member_id' in tr_cols:
        with op.batch_alter_table('task_recurrence_series', schema=None) as batch_op:
            try:
                batch_op.drop_index(batch_op.f('ix_task_recurrence_series_member_id'))
            except Exception:
                pass
            batch_op.drop_column('member_id')

    task_cols = [c['name'] for c in inspector.get_columns('tasks')]
    if 'member_id' in task_cols:
        with op.batch_alter_table('tasks', schema=None) as batch_op:
            try:
                batch_op.drop_index(batch_op.f('ix_tasks_member_id'))
            except Exception:
                pass
            batch_op.drop_column('member_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'family_members', ['member_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_tasks_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('task_recurrence_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'family_members', ['member_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_task_recurrence_series_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('recurrence_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'family_members', ['member_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_recurrence_series_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'family_members', ['member_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_agenda_events_member_id'), ['member_id'], unique=False)

    op.drop_table('task_members')
    op.drop_table('task_recurrence_series_members')
    op.drop_table('agenda_event_members')
    op.drop_table('recurrence_series_members')
    # ### end Alembic commands ###
